TemplateProviderCompany: Add validation of company ids
Company ids are critical, when converting from Excel to
ICompanyData.

If input Excel is missing company ids, then following
conversion raises a hard-to-debug exception:

~~~~
ValueError: Shape of passed values is (265, 6), indices imply (260, 6)
~~~~

With this commit, we prevent further convertion, and raise a
more understandable exception:

~~~~
ValueError: Missing company ids
~~~~

Signed-off-by: Kirill Marinushkin <k.marinushkin@gmail.com>